name: "Bug report"
description: Report a bug for this project.
labels: ["bug", "🔍 Ready for Review"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Provide a detailed explanation of your use case.
    validations:
      required: true
  - type: textarea
    id: code-snippet
    attributes:
      label: Code snippet
      description: Provide a code snippet where you are getting issue.
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current behaviour
      description: A output after code execution including stack traces, debug logs, etc.
      placeholder: Currently ..
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Golang version
      description: What version of Golang your using?
      placeholder: go1.18.4
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of go-ipfs-log package you are using?
      placeholder: v1.8.0
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What is your development environment?
      placeholder: Linux Ubuntu v20.04
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      placeholder: Any other detail?
